name: Renovate checks
concurrency:
  group: renovate-checks-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  renovate_checks:
    name: Renovate checks
    uses: ./.github/workflows/reusable_renovate_checks.yml
