on:
  workflow_call:
    inputs:
      checks_enabled:
        type: string
        default: '["tf_fmt", "trivy_config_scan", "tflint", "terraform_docs"]'
      working_directory:
        type: string
        default: "./"
        description: Working directory for the checks to run in
      tf_fmt_args:
        type: string
        default: -recursive -check -diff
        description: Arguments to pass to "terraform fmt"
      trivy_skip_dirs:
        type: string
        default: ""
        description: Comma separated list of directories where traversal is skipped
      tflint_config:
        type: string
        default: ${GITHUB_WORKSPACE}/.tflint.hcl
        description: TFLint config file path
      tflint_args:
        type: string
        default: --recursive --color
        description: Arguments to pass to "tflint"

jobs:
  tf_fmt:
    name: run terraform fmt
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson(inputs.checks_enabled), 'tf_fmt') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      - name: Run terraform fmt
        run: terraform fmt ${{ inputs.tf_fmt_args }} ${{ inputs.working_directory }}

  trivy_config_scan:
    name: run trivy config scan
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson(inputs.checks_enabled), 'trivy_config_scan') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run trivy config scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          scan-type: config
          scan-ref: ${{ inputs.working_directory }}
          skip-dirs: ${{ inputs.trivy_skip_dirs }}
          exit-code: '1'
          format: table

  tflint:
    name: run tflint
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson(inputs.checks_enabled), 'tflint') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        name: Setup TFLint
        with:
          tflint_version: latest
      - name: Init TFLint
        run: tflint --init -c ${{ inputs.tflint_config }}
      - name: Run TFLint
        run: tflint -c ${{ inputs.tflint_config }} ${{ inputs.tflint_args }}

  terraform_docs:
    name: run terraform-docs
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson(inputs.checks_enabled), 'terraform_docs') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Validate terraform docs are present and valid
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          find-dir: ${{ inputs.working_directory }}
          fail-on-diff: true
      - name: List README.md diff files
        if: ${{ failure() }}
        run: |
          git status
          echo "## run terraform-docs failure" >> $GITHUB_STEP_SUMMARY
          echo "### Newly generated or changed README.md files" >> $GITHUB_STEP_SUMMARY
          echo "There should be no new files generated by terraform-docs" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          git status >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
