on:
  workflow_call:

jobs:
  renovate_config_validator:
    name: renovate config validator
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:latest
      options: --user root # root is needed for checkout to work
    steps:
      - uses: actions/checkout@v4
      - name: Validate Renovate config
        run: renovate-config-validator --strict
