name: Terraform checks
concurrency:
  group: tf-checks-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tf_checks:
    name: Run Terraform sanity checks
    uses: ./.github/workflows/reusable_tf_checks.yml
